export const FETCH_BOARDS_REQUEST = 'FETCH_BOARDS_REQUEST';
export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
export const CREATE_BOARD_REQUEST = 'CREATE_BOARD_REQUEST';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const FETCH_BOARD_REQUEST  = 'FETCH_BOARD_REQUEST';
export const FETCH_BOARD_SUCCESS  = 'FETCH_BOARD_SUCCESS';

export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const UPDATE_LIST_REQUEST = 'UPDATE_LIST_REQUEST';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';

export const SHOW_CREATE_BOARD_FORM = 'SHOW_CREATE_BOARD_FORM';
export const HIDE_CREATE_BOARD_FORM = 'HIDE_CREATE_BOARD_FORM';
export const UPDATE_CREATE_BOARD_FORM_INPUT_TEXT = 'UPDATE_CREATE_BOARD_FORM_INPUT_TEXT';

export const SHOW_CREATE_LIST_FORM = 'SHOW_CREATE_LIST_FORM';
export const HIDE_CREATE_LIST_FORM = 'HIDE_CREATE_LIST_FORM';
export const UPDATE_CREATE_LIST_FORM_INPUT_TEXT = 'UPDATE_CREATE_LIST_FORM_INPUT_TEXT';

export const CREATE_CARD_REQUEST = 'CREATE_CARD_REQUEST';
export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';
export const FETCH_CARD_REQUEST = 'FETCH_CARD_REQUEST';
export const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS';
export const UPDATE_CARD_REQUEST = 'UPDATE_CARD_REQUEST';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';

export const TOGGLE_COLORBLIND = 'TOGGLE_COLORBLIND';
